Default: &defaults
  user: sample
  password: sample
  host: localhost
  port: 5432
  database: sample
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sample_test
  <<: *defaults

Staging:
  database: sample_staging
  poolsize: 100
  <<: *defaults

Production:
  database: sample_production
  poolsize: 100
  <<: *defaults
